services:
  nginx:
    container_name: exertion-app_nginx-dev
    build:
      context: ./client
      target: nginx-dev
    environment:
      WEBPACK_SERVER: http://web:3000/
      GRAPHQL_BACKEND: http://apollo:4000/
      SUBSCRIPTION_BACKEND: http://apollo:4000/subscriptions
    ports:
      - "3000:80"
    links:
      - web
  web:
    container_name: exertion-app_web-dev
    build:
      target: web-dev
    environment:
      GRAPHQL_BACKEND: http://apollo:4000/
      SUBSCRIPTION_BACKEND: http://apollo:4000/subscriptions
    volumes:
      - ./client:/build
    links:
        - apollo
  apollo:
    container_name: exertion-app_apollo-dev
    build:
      target: backend-dev
    environment:
      MONGODB_URI: mongodb://exertion:exertion@mongo/exertion?retryWrites=true
      JWT_SECRET: ssshhh
    volumes:
      - ./server:/app
  mongo:
    container_name: exertion-app_mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodb-volume:/data/db
      - ./server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
volumes:
  mongodb-volume: {}