services:
  web:
    image: exertion-app_web-prod
    build:
      target: web-prod
    image: web-prod
    ports:
      - "80:80"
    environment:
      GRAPHQL_BACKEND: http://apollo:4000/
      SUBSCRIPTION_BACKEND: http://apollo:4000/subscriptions
    links:
        - apollo
  apollo:
    image: exertion-app_apollo-prod
    build:
      target: backend-prod
    image: backend-prod
    environment:
      MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo/exertion?retryWrites=true
      JWT_SECRET: ${JWT_SECRET}
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb-volume:/data/db
      - ./server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
    mongodb-volume: {}